### ISSUE TITLE
RabbitMQ URL

### ISSUE THREAD

**Issue by mlb1621** [wadoadi/Google-Assistant-SkyHD-Box-Integration#1]
I can't seem to get the correct AMQP URL for IFFFT to fire it, any pointers?

**Comment by wadoadi** [comment]
So I assume you found exchanges 
https://mosquito.rmq.cloudamqp.com/#/exchanges And added one?

If so then returning to the details page your url should be shown there next to AMQP URL, you just need to add the exchange to the end so it will look smething like 
https://YourDetails@mosquito.rmq.cloudamqp.com/api/exchanges/xhbuefux/google.home.assistant/publish

Hope it helps!?

**Comment by mlb1621** [comment]
Thanks for coming back to me!

Yes I've created the exchange and the queue and added the binding.

The URL I'm given on the details page is
amqp://gnfolxxv:xxxxxxxxxxxxxxxxxxxxx@bee.rmq.cloudamqp.com/gnfolxxv
If I use this in the config.ini on the raspberry pi it connects successfully and I can see the connection in RabbitMQ Manager.

If I enter the URL in IFTTT as https://gnfolxxv:xxxxxxxxxxxxxxxxxxxxx@bee.rmq.cloudamqp.com/api/exchanges/gnfolxxv/google.home.assistant/publish
Then I get "Your server returned a 400".  Also, if I use this URL in the config,ini I get connection failed.

If I use
https://gnfolxxv:xxxxxxxxxxxxxxxxxxxxx@bee.rmq.cloudamqp.com/gnfolxxv/exchanges/google.home.assistant/publish
Then I get "Your server returned a 405" but if I use this in the config,ini then it connects.

Apologies if I've missed something obvious!

--

**Comment by mlb1621** [comment]
OK so I've figured out that it's the formatting of the payload, the 400 was a bad_request not_json, and removing "payload":"{"command": "command", "value": " {{TextField}}"}" and sending "payload":"" fires from IFTTT but obviously doesn't work...

**Comment by mlb1621** [comment]
Got this working, had to escape out the payload string with single quotes,

{ "properties":{ "content-type":"application/json" }, "routing_key":"skyhdbox.smart.tv", "payload":'{"command": "command", "value": " {{TextField}}"}', "payload_encoding":"string" }

 And in skyhdgooglecontrol.py change the datetime.datetime.now() to str(datetime.datetime.now())

Works a treat!

**Comment by mgarland1988** [comment]
> Got this working, had to escape out the payload string with single quotes,
> 
> { "properties":{ "content-type":"application/json" }, "routing_key":"skyhdbox.smart.tv", "payload":'{"command": "command", "value": " {{TextField}}"}', "payload_encoding":"string" }
> 
> And in skyhdgooglecontrol.py change the datetime.datetime.now() to str(datetime.datetime.now())
> 
> Works a treat!

Mattleebrown - this is the same issue that I had.

So i have the following URL:

amqp://XXXXXXXXXXX:RandomUser@crow.rmq.cloudamqp.com/RandomUser

So if I edit the body as you did and edit the skyhdgooglecontrol.py file, this should hopefully work?

The other area that I am unsure on is adding the phrase in IFTTT

Would I need to enter every single action that I want to automate actions e.g. okay google, channel 1 0 3 etc.........................(I am sorry for my lack of understanding). 

Also is the correct format: Okay Google, channel 1 0 1 $

Appreciate your help!

**Comment by mlb1621** [comment]
Hi,

Sorry I have only just seen this so you might have this sorted already, yes that should work, and no you don't need to add each action, these get passed on from google assistant as the ingredient.

I set 'What do you want to say?' as 'Sky $' on ifttt', so I just say 'hey google, sky xxx', but obviously you could set this to something else.

Thanks
