### ISSUE TITLE
Google Home Intergation Sky Q

### ISSUE THREAD

**Issue by mgarland1988** [wadoadi/Google-Assistant-SkyHD-Box-Integration#2]
This is an excellent resource.

This is not really an issue, but does anyone have this working with Sky Q?

I have the sky-remote-cli commands working from my Pi.

Do I need to make any other changes to configuration / script files?

Many thanks

**Comment by wadoadi** [comment]
Hi, not yet it is on my list to look at as I now have SkyQ too, but I never used it that much after doing it with sky HD so it's a long way down the list!

**Comment by mgarland1988** [comment]
Thank you for your help. I am in the process of testing this.

As your instructions say, I have installed "npm install -g sky-remote-cli" and i CAN confirm that the commands work for a Sky Q box.

For example, when I type: "sky-remote-cli 192.168.0.40 1 0 1" on the Raspberry Pi, the Sky Q box will change to channel 101

Therefore, if I follow the rest of the guide, should this work for my Sky Q box? With regards to the "Config.ini" file, would I just need to enter the IP address for the sky box for the host, and leave the name at "SkyHD"? 

Thank you for your help and guidance
